server:
  port: 8080

spring:
  

minio:
  endpoint: http://127.0.0.1:9000      # MinIO的服务地址
  fileHost: http://127.0.0.1:9000      # 文件地址host
  bucketName: ai-interviewer           # 存储桶bucket的名称
  accessKey: 83AvOqpz1Plu5E53EDZG      # 访问密钥Access Key
  secretKey: lYuWZK7yx1oSCYwiwK2ziPH637fOTK55w4yGCvxi  # 密钥Secret Key

