server:
  port: 8080

spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://127.0.0.1:4406/agent_interviewer?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: DataSourceHikariCP           # 连接池的名字
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: 127.0.0.1     # 填写redis服务所在的ip地址（建议内网ip）
      port: 5379
      database: 0
      password: 123456

minio:
  endpoint: http://127.0.0.1:9000      # MinIO的服务地址
  fileHost: http://127.0.0.1:9000      # 文件地址host
  bucketName: ai-interviewer           # 存储桶bucket的名称
  accessKey: 83AvOqpz1Plu5E53EDZG      # 访问密钥Access Key
  secretKey: lYuWZK7yx1oSCYwiwK2ziPH637fOTK55w4yGCvxi  # 密钥Secret Key

xunfei:
  appId: a006ee60
  apiKey: d98ad0cb6bfd95a28eefd794415cc48f
  apiSecret: OTdmNzliNjVlNjdmZjA1NmI4MzU1YjFj

xf:
  config:
    hostUrl: https://spark-api.xf-yun.com/v4.0/chat
    appId: a006ee60
    apiSecret: OTdmNzliNjVlNjdmZjA1NmI4MzU1YjFj
    apiKey: d98ad0cb6bfd95a28eefd794415cc48f
    maxResponseTime: 40

tts:
  voiceSource: D:/xz/agent-interviewer/voice_source/

aliyun: #阿里云的配置
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5tSH44Mm2phtyuj5tfom
      secret-access-key: VrGAuQ5CTDdqI2BFXNI8EsMqtweDSQ
      bucket: pic--oss
